"""init

Revision ID: 923d489b546d
Revises: 
Create Date: 2026-02-17 02:06:32.265102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923d489b546d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport',
    sa.Column('airport_code', sa.String(), nullable=False),
    sa.Column('airport_name', sa.String(), nullable=False),
    sa.Column('airport_country', sa.String(), nullable=False),
    sa.Column('airport_city', sa.String(), nullable=False),
    sa.Column('airport_address', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('airport_code')
    )
    op.create_table('route',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('origin_airport_code', sa.String(), nullable=False),
    sa.Column('destination_airport_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('aircraft',
    sa.Column('aircraft_id', sa.UUID(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('aircraft_model', sa.String(), nullable=False),
    sa.Column('current_distance', sa.Float(), nullable=False),
    sa.Column('maintenance_interval', sa.Float(), nullable=False),
    sa.Column('aircraft_status', sa.Enum('AVAILABLE', 'DEPLOYED', 'AOG', name='aircraft___status'), nullable=False),
    sa.Column('aircraft_location', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_location'], ['airport.airport_code'], ),
    sa.PrimaryKeyConstraint('aircraft_id')
    )
    op.create_table('in_flight_employee',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('position', sa.Enum('CAPTAIN', 'COPILOT', 'FLIGHT_MANAGER', 'FLIGHT_ATTENDANT', name='employee___position'), nullable=False),
    sa.Column('employee_status', sa.Enum('AVAILABLE', 'SCHEDULED', name='inflight___status'), nullable=False),
    sa.Column('supervisor', sa.UUID(), nullable=False),
    sa.Column('employee_location', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employee_location'], ['airport.airport_code'], ),
    sa.ForeignKeyConstraint(['supervisor'], ['in_flight_employee.employee_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('flight',
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('flight_status', sa.Enum('SCHEDULED', 'IN_FLIGHT', 'ARRIVED', 'DELAYED', 'CANCELLED', name='flight___status'), nullable=False),
    sa.Column('aircraft_id', sa.UUID(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.aircraft_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.route_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_table('flight_crew',
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['in_flight_employee.employee_id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.flight_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('flight_id', 'employee_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_crew')
    op.drop_table('flight')
    op.drop_table('in_flight_employee')
    op.drop_table('aircraft')
    op.drop_table('route')
    op.drop_table('airport')
    # ### end Alembic commands ###
